This project is created by Jamal Hussain Shah on 25-5-2022


# Course - Introduction to R 

##### NOTE: 
1. Your code MUST execute without any errors. 
2. You can add more lines in your code as required.

## Section 1: Data Types and Operations Pt. 1

### Question 1 
**Create the variables with the following composition:**
1. A vector containing each letter of your first name as its elements.
2. A variable that contains your name concatenated from the vector created in (1)
3. A variable containing a sequence from 100 to 120.
4. Create a matrix of 3x3 dimensions that contains the even sequence of numbers starting from 2.
5. Assign names to the variables.

In [1]:
x <- "jamal"
x

[1] "jamal"

In [2]:
x <- c("j","a","m","a","l")
x

[1] "j" "a" "m" "a" "l"

In [5]:
myname <- c("jamal")
name <- paste('may name is', myname)
name

[1] "may name is jamal"

In [6]:
sequence <- 100:120
sequence

[1] 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
[20] 119 120

In [7]:
nmatrix <- matrix(seq(from = 2, length.out = 9, by = 2), 3 , 3)
nmatrix

[,1] [,2] [,3]
[1,] 2     8   14  
[2,] 4    10   16  
[3,] 6    12   18

In [8]:
names(myname) <- "firstName"
names(name) <- "ConcatName"
names(sequence) <- "seq_series"
names(nmatrix) <- "evenmatrix"
myname
name
sequence
nmatrix

firstName 
  "jamal"

ConcatName 
"may name is jamal"

seq_series       <NA>       <NA>       <NA>       <NA>       <NA>       <NA> 
       100        101        102        103        104        105        106 
      <NA>       <NA>       <NA>       <NA>       <NA>       <NA>       <NA> 
       107        108        109        110        111        112        113 
      <NA>       <NA>       <NA>       <NA>       <NA>       <NA>       <NA> 
       114        115        116        117        118        119        120

[,1] [,2] [,3]
[1,] 2     8   14  
[2,] 4    10   16  
[3,] 6    12   18

### Question 2
**Create a factor variable emp_status:**
1. Containing the categorical variables: Employed, Unemployed, Self-Employed, with each level appearing atleast more than 2.
2. Display the levels and the factor variable as a table.
3. Unclass the elements of the factor variable.

In [ ]:
#### Start solution ####

In [66]:
factorization <- factor(c("Employed","Unemployed","Self-Employed","Employed","Unemployed","Self-Employed"))
levels = c("Employed","Self-Employed","Unemployed")
factorization

[1] Employed      Unemployed    Self-Employed Employed      Unemployed   
[6] Self-Employed
Levels: Employed Self-Employed Unemployed

In [64]:
table(factorization)

factorization
     Employed Self-Employed    Unemployed 
            2             2             2 

In [65]:
unclass(factorization)

[1] 1 3 2 1 3 2
attr(,"levels")
[1] "Employed"      "Self-Employed" "Unemployed"

In [ ]:
#### End solution ####

### Question 3
**Create a dataframe object called bank_customers:**
1. the data frame will have three columns: CustomerID, hasAccount, totalBalance
2. Fill the data as follows
    a. Alicia does not have an account. She is here for inquiry 
    b. Nancy is here to check on her account balance of USD 10,000.
    c. Fernando is here to deposit USD 100 in his account which had no balance.
    d. Louis will withdraw all his money from the account that had USD 2,000. 
    e. Diane is here for information. 
3. For customers that do not have a value, use NA as placeholder.
4. Print the number of rows, columns and names for the data frame.

In [72]:
CustomerID <- c("Alicia","Nancy","Fernando","Louis","Diane")
hasAccount <- c(F,T,T,T,F)
totalBalance <- c(NA,10000,100,2000,NA)
customerdata <- data.frame(CustomerID,hasAccount,totalBalance)
customerdata



CustomerID hasAccount totalBalance
1 Alicia     FALSE         NA       
2 Nancy       TRUE      10000       
3 Fernando    TRUE        100       
4 Louis       TRUE       2000       
5 Diane      FALSE         NA

In [73]:
is.na(customerdata)

CustomerID hasAccount totalBalance
[1,] FALSE      FALSE       TRUE       
[2,] FALSE      FALSE      FALSE       
[3,] FALSE      FALSE      FALSE       
[4,] FALSE      FALSE      FALSE       
[5,] FALSE      FALSE       TRUE

In [74]:
nrow(customerdata)

[1] 5

In [75]:
ncol(customerdata)

[1] 3

In [76]:
names(customerdata)

[1] "CustomerID"   "hasAccount"   "totalBalance"

In [ ]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 2: Control Structures 

### Question 1
**Create a variable containing a sequence of numbers from 1 to 100:**
1. Iterate over the variables and print those numbers which are prime.

**Create a variable var with a value of 1:**
1. Create a while loop and increase the value of var at each iteration. 
2. When you reach the 10th prime number, terminate the loop and print the number.

In [ ]:
#### Start solution ####

In [78]:
num_seq <- c(1:100)
num_seq


[1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
 [19]  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
 [37]  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
 [55]  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
 [73]  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
 [91]  91  92  93  94  95  96  97  98  99 100

In [98]:
for (i in num_seq){
    number <- num_seq[i]
    if(number%%2 > 0 &&  number%%5 >0){
        print(num_seq[i])
    }
    
}

[1] 1
[1] 3
[1] 7
[1] 9
[1] 11
[1] 13
[1] 17
[1] 19
[1] 21
[1] 23
[1] 27
[1] 29
[1] 31
[1] 33
[1] 37
[1] 39
[1] 41
[1] 43
[1] 47
[1] 49
[1] 51
[1] 53
[1] 57
[1] 59
[1] 61
[1] 63
[1] 67
[1] 69
[1] 71
[1] 73
[1] 77
[1] 79
[1] 81
[1] 83
[1] 87
[1] 89
[1] 91
[1] 93
[1] 97
[1] 99


In [ ]:
z <- 1
while()

In [ ]:
#### End solution ####

### Question 2
**Create a matrix of size 3x3 called mat_1:**
1. Iterate over all the values one by one and print the element as well as the position in the matrix (row, col)

In [ ]:
#### Start solution ####

In [100]:
mat_1 = matrix(data = 1:9, nrow=3, ncol=3)
mat_1
for (row in 1:3){
  for (col in 1:3){
    print(paste0("position at  ", row, "x", col, " = ", mat_1[row, col]))
  }
}

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[1] "position at  1x1 = 1"
[1] "position at  1x2 = 4"
[1] "position at  1x3 = 7"
[1] "position at  2x1 = 2"
[1] "position at  2x2 = 5"
[1] "position at  2x3 = 8"
[1] "position at  3x1 = 3"
[1] "position at  3x2 = 6"
[1] "position at  3x3 = 9"


In [ ]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 3: Functions

### Question 1
**Create a function called gcd that finds the greatest common divisor of two numbers a and b:**
1. a and b, should be taken as input.
2. The function must print the GCD as well as return it.
3. The output must be saved in a variable called answer.

In [ ]:
#### Start solution ####

In [106]:
gcd <- function(a,b) {
  
  if( a > b ){
    max_num = a
    } else {
      max_num = b
    }
    for (i in 1:max_num) {
      if ((a %% i == 0) && (b %% i == 0)) {
        ret = i
      }
    }
    return(ret)
}


answer <- gcd(150, 27)
answer

[1] 3

In [ ]:
#### End solution ####

### Question 2
**Create a function called allConditionsMeet, that checks whether two expressions evaluate to true:**
1. a and b, should be taken as input.
2. the function should check if a and b, both conditions, evaluate to True.
3. The function must returns a boolean value.
4. Using a method, print the arguments that function takes.

In [ ]:
#### Start solution ####

In [110]:
allConditionsMeet <- function(a,b){
    if(a==b){
        return(TRUE)
    }else{
        return(FALSE)
    }
}
allConditionsMeet(5,6)

[1] FALSE

In [111]:
print(args(allConditionsMeet))

function (a, b) 
NULL


In [ ]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 4: Vectorized Operations

### Question 1
**Create two matrices matrix_1 and matrix_2 of dimensions 2x3 and 3x2:**
1. Perform element-wise multiplication.
2. Perform matrix multipilcation. 

**Create a 2x2 matrix my_mat:**
1. Write a function to find the determinant of the matrix.

In [ ]:
#### Start solution ####

In [126]:
matrix_1 <- matrix(2:7,2,3)
matrix_2 <- matrix(8:13,3,2)
matrix_1
matrix_2


[,1] [,2] [,3]
[1,] 2    4    6   
[2,] 3    5    7

[,1] [,2]
[1,]  8   11  
[2,]  9   12  
[3,] 10   13

In [127]:
print(matrix_1*t(matrix_2))

     [,1] [,2] [,3]
[1,]   16   36   60
[2,]   33   60   91


In [128]:
print(matrix_1 %*% matrix_2)

     [,1] [,2]
[1,]  112  148
[2,]  139  184


In [130]:
my_mat = matrix(6:9, 2, 2)
my_mat
print(det(my_mat))

[,1] [,2]
[1,] 6    8   
[2,] 7    9

[1] -2


In [ ]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 5: Date and Time in R

### Question 1
**Use the current date and time and store them into variables curr_date and curr_time respectively: [use sys]**
1. Convert both into date and time objects using the appropriate functions.
2. Print the weekday, year, second and hour using the appropriate function and variables.

In [ ]:
#### Start solution ####

In [131]:
curr_date <- Sys.Date()
curr_time <- Sys.time()
curr_date
curr_time

[1] "2022-03-03"

[1] "2022-03-03 13:20:08 PKT"

In [138]:
class(curr_date)
class(curr_time)


[1] "Date"

[1] "POSIXct" "POSIXt"

In [140]:
curr_date <- as.POSIXlt(curr_date)
curr_time <- as.POSIXlt(curr_time)
names(unclass(curr_time))

[1] "sec"    "min"    "hour"   "mday"   "mon"    "year"   "wday"   "yday"  
 [9] "isdst"  "zone"   "gmtoff"

In [141]:
curr_time$wday
curr_time$year
curr_time$sec
curr_time$hour

[1] 4

[1] 122

[1] 8.588969

[1] 13

In [ ]:
#### End solution ####

### Question 2
**Create a variable to store current date/time**
1. Create another variable that stores and set the timezone as GMT-5
2. Find the difference between your current time and the GMT-5 timezone.

In [ ]:
#### Start solution ####

In [142]:
curr_time <- as.POSIXct(Sys.time())
curr_time


[1] "2022-03-03 13:26:16 PKT"

In [143]:
gmt_currtime <- as.POSIXct("2021-12-01 05:36:29" ,tz = 'GMT')
gmt_currtime

[1] "2021-12-01 05:36:29 GMT"

In [144]:
curr_time - gmt_currtime

Time difference of 92.11792 days

In [ ]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 6: Loop Functions

### Question 1
**Create a function to calculate mean and standard deviation of the provided data**
1. Create a sequence of numbers from 100 to 150 store in a variable called numbers.
1. Use lapply, sapply, apply and tapply to implement the functions on "numbers" [only on the second half of the sequence for tapply]

In [ ]:
#### Start solution ####

In [146]:
numbers <- list(100:150)


In [151]:
lapply(numbers, mean)
lapply(numbers, sd)

[[1]]
[1] 125

[[1]]
[1] 14.86607

In [152]:
sapply(numbers, mean)
sapply(numbers, sd)

[1] 125

[1] 14.86607

In [165]:
x <- matrix(rnorm(number),10,10)

apply(x, 2, mean)
apply(x, 2, sd)

[1]  0.07651148 -0.33840568 -0.34385502 -0.23072741  0.30225683 -0.42160683
 [7] -0.09607000  0.22738484  0.06486503 -0.21765190

[1] 1.1243171 0.6954284 1.0223033 0.7958310 0.8082406 0.9812247 0.8680750
 [8] 1.3989765 0.8077130 0.9407122

In [174]:
numbers  <- c(101:150)

half <- gl(2,length(numbers)/2)


tapply(numbers, half, mean)
tapply(numbers, half, sd)

1   2 
113 138

1        2 
7.359801 7.359801

In [ ]:
#### End solution ####

### Question 2
**Create a matrix of dimensions 4x4**
1. Find the row-wise and column-wise mean of the matrix.
2. Print the values.

In [ ]:
#### Start solution ####

In [179]:
num_matrix <- matrix(rnorm(16), 4, 4)
num_matrix

[,1]       [,2]       [,3]       [,4]      
[1,] -1.1891402 -0.5621150  0.8165698  0.8876525
[2,]  0.1641317 -1.5955532 -0.6190930 -1.9457432
[3,] -2.3899499  0.3545693 -1.1083007  0.3459636
[4,]  0.1459202  0.7123108 -0.9472979  0.6391232

In [182]:
mean_row <- apply(num_matrix, 1, mean)
mean_row


[1] -0.01175825 -0.99906443 -0.69942942  0.13751409

In [183]:
mean_col <- apply(num_matrix, 2, mean)
mean_col

[1] -0.8172595 -0.2726970 -0.4645305 -0.0182510

In [ ]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 7: Data Split

### Question 1
**Using the data frame Orange:**
1. Using split function to break down the dataset on circumference and store it in 'split_data' variable. 
2. Print the values for split_data where circumference is 30 and 75.
3. Find the average age of the tree when the circumference is 30 and when circumference is 214.


The dataset is loaded and the variable Orange contains the respective dataset.

In [184]:
library(datasets)

In [185]:
head(Orange)

Tree age  circumference
1 1     118  30          
2 1     484  58          
3 1     664  87          
4 1    1004 115          
5 1    1231 120          
6 1    1372 142

In [ ]:
#### Start solution ####

In [187]:
split_data <- split(Orange, Orange$circumference)
split_data

$`30`
   Tree age circumference
1     1 118            30
15    3 118            30
29    5 118            30

$`32`
   Tree age circumference
22    4 118            32

$`33`
  Tree age circumference
8    2 118            33

$`49`
   Tree age circumference
30    5 484            49

$`51`
   Tree age circumference
16    3 484            51

$`58`
  Tree age circumference
2    1 484            58

$`62`
   Tree age circumference
23    4 484            62

$`69`
  Tree age circumference
9    2 484            69

$`75`
   Tree age circumference
17    3 664            75

$`81`
   Tree age circumference
31    5 664            81

$`87`
  Tree age circumference
3    1 664            87

$`108`
   Tree  age circumference
18    3 1004           108

$`111`
   Tree age circumference
10    2 664           111

$`112`
   Tree age circumference
24    4 664           112

$`115`
   Tree  age circumference
4     1 1004           115
19    3 1231           115

$`120`
  Tree  age circumference
5    1 1231           120

$`125`
   Tree  age circumference
32    5 1004           125

$`139`
   Tree  age circumference
20    3 1372           139

$`140`
   Tree  age circumference
21    3 1582           140

$`142`
   Tree  age circumference
6     1 1372           142
33    5 1231           142

$`145`
  Tree  age circumference
7    1 1582           145

$`156`
   Tree  age circumference
11    2 1004           156

$`167`
   Tree  age circumference
25    4 1004           167

$`172`
   Tree  age circumference
12    2 1231           172

$`174`
   Tree  age circumference
34    5 1372           174

$`177`
   Tree  age circumference
35    5 1582           177

$`179`
   Tree  age circumference
26    4 1231           179

$`203`
   Tree  age circumference
13    2 1372           203
14    2 1582           203

$`209`
   Tree  age circumference
27    4 1372           209

$`214`
   Tree  age circumference
28    4 1582           214

In [188]:
split_data$`30`
split_data$`75`
apply <- function(x) colMeans(x[, c("Tree", "circumference")], na.rm = TRUE)
apply

Tree age circumference
1  1    118 30           
15 3    118 30           
29 5    118 30

Tree age circumference
17 3    664 75

function(x) colMeans(x[, c("Tree", "circumference")], na.rm = TRUE)

In [ ]:
#### End solution ####


### Save it and push .ipynb and .html file to your Github Repository
## GOOD JOB! You have successfully finished the course!